# This is a basic workflow that is manually triggered

name: Create video and upload to telegram

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Install python
      run: sudo apt-get install -y python3.9
      
    - name: Install Node
      run: sudo apt-get install -y nodejs
      
    - name: Install ffmpeg
      run: sudo apt-get install ffmpeg
    
    - name: Clone Repo
      run: git clone https://github.com/yogeshwaran01/create-video-upload-to-telegram.git
    
    - name: Install Dependenices
      run: python -m pip install -r requirements.txt && npm install
    
    - name: Run Bot
      run: ./bot.sh
